#!/bin/sh

lua_file=$1
base=${lua_file%.lua}
c_file="$base"_aot.c
so_file="$base"_aot.so

echo "Generating $c_file ..."
../src/luaot "$lua_file" -o "$c_file" || exit 1

echo "Compiling $so_file ..."
gcc -shared -fPIC -O2 -g -I../src "$c_file" -o "$so_file" || exit 1

echo "Done!"
exit 0
